apiVersion: v1
kind: Namespace
metadata:
 name: jsalto
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: assign-03-statefulset
  namespace: jsalto
  labels:
    app: assign-03-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assign-03-app
  template:
    metadata:
      labels:
        app: assign-03-app
    spec:
      containers:
      - name: assign-03-container
        image: tysalto/comp4016:assign03
        readinessProbe:
          exec:
            command: ["curl", "-f", "http://assign-03-is-alive-service-internal.jsalto.svc.cluster.local:30009/isAlive"]
          # httpGet:
          #   path: /isAlive          # Path to check on Pod B
          #   port: 30009             # Port exposed by the service
          #   host: assign-03-is-alive-service-internal.jsalto.svc.cluster.local
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        volumeMounts:
        - name: data-vol
          mountPath: /data/jsalto
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: assign-03-service
  namespace: jsalto
spec:
  selector:
    app: assign-03-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assign-03-hpa
  namespace: jsalto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: assign-03-statefulset
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign-03-is-alive-deployment
  namespace: jsalto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: is-alive
  template:
    metadata:
      labels:
        app: is-alive
    spec:
      containers:
      - name: is-alive
        image: tysalto/comp4016:assign03
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /isAlive
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: assign-03-is-alive-service-internal
  namespace: jsalto
spec:
  selector:
    app: is-alive
  ports:
    - protocol: TCP
      port: 30009      # External port exposed by the Service
      targetPort: 8080 # Port used by the container
---
apiVersion: v1
kind: Service
metadata:
  name: assign-02-is-alive-service-external
  namespace: jsalto
spec:
  selector:
    app: is-alive
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30010